sensor:
  - platform: pulse_counter
    pin: GPIO17
    unit_of_measurement: 'L/min'
    name: 'Gas flow'
    accuracy_decimals: 3
    update_interval: 20s
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    filters:
      - lambda: return x * ((1.0 / 1000) * 1000);
    total:
      unit_of_measurement: 'm³'
      name: 'Gas total'
      accuracy_decimals: 3
      device_class: gas
      state_class: total_increasing
      filters:
        - lambda: return x * (1.0 / 1000);
